#Minecraft server properties
#Wed Aug 05 21:19:31 CEST 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
difficulty=hard
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=Lqre7RIQcoVzihHkWZ37irb8ZdlzmhV8RphgkhU7
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=Ako radi kopija servera udji u njega. Ako ne, pokreni svoj. Nakon sto ga ugasis pushaj na github.
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https\://github.com/SirBoi/minecraft-servers/releases/download/resource-pack/Resource.pack.26.2.zip
resource-pack-id=
resource-pack-prompt={"text"\:"Najjaci resource pack, vjeruj mi brate, najjaci je, vjeruj bratu."}
resource-pack-sha1=66fb23e10e75a90c54ae5fd10a893f6183db12b4
server-ip=
server-port=25565
simulation-distance=12
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=32
white-list=false
